config/routes.rb
Rails.application.routes.draw do

	resources :users
	resources :songs
	
	root 'users#new'

	get 	'login'		=> 'sessions#new'
	get 	'songs'		=> 'songs#index'
	get 	'songs/new' => 'songs#new'
	
	post 	'login'		=> 'sessions#create'
	post 	'songs'		=> 'songs#create'
	
	delete 	'logout'	=> 'sessions#destroy'
	
	

end

app/models/song.rb
class Song < ActiveRecord::Base
	has_attached_file :upload
	belongs_to :user
	
	validates_attachment_presence :upload
	validates_attachment_size :upload, :less_than => 10.megabytes
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :songs

	before_save { self.email = email.downcase }
	
	validates :name, 	presence: true, length: { maximum: 50 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, 	presence: true, length: { maximum: 255}, 
						format: { with: VALID_EMAIL_REGEX }, 
						uniqueness: { case_sensitive: false }
	
	has_secure_password
	validates :password, length: { minimum: 6 }
	 
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to user
		else
			flash.now[:danger] = 'Invalid email/password combination'
			render 'new'
		end
	end
	
	def destroy
		log_out
		redirect_to root_url
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	#GET /songs
	def index
		@songs = Song.all
	end
	
	#GET /songs/new
	def new 
		@song = Song.new
	end
	
	#POST /songs
	def create
		@song = Song.new(song_params)
		if @song.save
			redirect_to action: 'index'
		else
			render 'new'
		end
	end
	
	private
		def song_params
			params.require(:song).permit(:upload)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome to CATastrophe!"
			redirect_to @user
		else
			render 'new'
		end
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
		base_title = "CATastrophe"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end
	
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end
	
	def logged_in?
		!current_user.nil?
	end
	
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<header class = "navbar nav-fixed-top navbar-inverse">
		<div class = "container">
			<%= link_to image_tag("logo-white-resize.png", alt: "CATastrophe logo"), 
			root_path, id: "logo" %>
			<nav>
				<ul class = "nav navbar-nav navbar-right">
					<%if logged_in? %> 
						<li><%= link_to "Songs", songs_path %></li>
						<li><%= link_to "Playlists", '#' %></li>
					<% else %>
						<li><%= link_to "Home", root_path %></li>
					<% end %>
					
					<% if logged_in? %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Settings", '#' %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Log out", logout_path, method: "delete" %>
								</li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</header>
	<footer class = "footer">
		<%if logged_in? %>
			<button onClick = "playPrev()">Prev</button>
			<button onClick = "playAudio("#")">Stop</button>
			<button onClick = "playNxt()">Next</button>
			<audio controls id =>
				<source src = "#" type = "audio/mp3">
			</audio>
			<i> Now Playing: -Song Title- </i> 
		<% end %>
	</footer>
	<div class = "container">
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%= message %></div>
		<% end %>
		<%= yield %>
		<!---<%= debug(params) if Rails.env.development? %> -->
	</div>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/songs/index.html.erb
<% provide(:title, "Songs") %>

<p>
	<h1 style="font-family: CuteTumblrFont; font-size:4em">Uploaded Songs</h1>
</p>

<%= link_to "Upload New Song", new_song_path %> 

<div id = 'ulsongs'>
	<% for song in @songs %>
		<%= link_to song.uploaded_song_file_name, playSong() %>
	<% end %>
</div>

app/views/songs/new.html.erb
<% provide(:title, "Upload") %>

<p>
	<h1 style="font-family: CuteTumblrFont; font-size:4em">Upload Song</h1>
</p>

<p>
	<%= form_for(@song, :html => { :multipart => true }) do |f| %>
		<%= f.file_field :uploaded_song %>
		<%= f.submit "Upload" %>
	<% end %>
</p>

<%= link_to "Back to Song List", songs_path %>

app/views/users/new.html.erb
<% provide(:title, "Home") %>

<div class = "jumbotron">
	<h1 style="font-family:CuteTumblrFont; font-size: 6em"><center> 
		CATastrophe</center></h1>
	
	<hr>
	
	<div class="row" style="font-family:LongTime; letter-spacing:2px">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>
			
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %> 

			<%= f.label :email %> 
			<%= f.text_field :email %> 
			
			<%= f.label :password %> 
			<%= f.password_field :password, class: 'form-control' %> 

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %> 
	

			<%= f.submit "Create Account", class: "btn btn-lg btn-primary" %> 
		<% end %>
	</div>
	
	<h2>
		Already have an account? <%= link_to "Log in here", login_path %> 
	
	 </h2> 
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				Welcome back <%= @user.name %>!
			</h1>
		</section>
	</aside>
</div>